# Generated by Django 4.0.3 on 2022-05-13 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_rename_sales_person_salerecord_salesperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecord',
            name='automobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_records', to='sales_rest.automobilevo'),
        ),
    ]
