# Generated by Django 4.0.3 on 2022-05-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_serviceappointment_is_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappointment',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
